//! Master Sound Presets: Dolby Atmos, Bang & Olufsen, Apple Spatial, DTS:X, Laptop Fix, etc.

use crate::dsp::earphone_profiler::EarphoneType;
use crate::dsp::environment_adapter::EnvironmentMode;
use crate::dsp::pipeline::PipelineConfig;
use crate::dsp::spatializer::SpatialMode;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Preset {
    pub name: String,
    pub description: String,
    pub eq_gains_10: [f32; 10], // 31, 63, 125, 250, 500, 1k, 2k, 4k, 8k, 16k
    pub master_gain_db: f32,
    pub ai_boost_enabled: bool,
    pub ai_intensity: f32,
    pub bass_boost_intensity: f32,
    pub bass_speaker_protect: bool,
    pub exciter_air_mix: f32,
    pub exciter_drive: f32,
    pub spatial_width: f32,
    pub spatial_depth: f32,
    pub spatial_crossfeed: f32,
    pub spatial_mode_headphone: bool, // true = headphones binaural, false = laptop speakers
    pub transient_attack: f32,
    pub compressor_intensity: f32,
    pub dynamic_loudness: f32,
}

impl Preset {
    pub fn to_pipeline_config(&self) -> PipelineConfig {
        PipelineConfig {
            enabled: true,
            master_gain_db: self.master_gain_db,
            ai_boost_enabled: self.ai_boost_enabled,
            ai_intensity: self.ai_intensity,
            bass_boost_intensity: self.bass_boost_intensity,
            bass_speaker_protect: self.bass_speaker_protect,
            exciter_air_mix: self.exciter_air_mix,
            exciter_drive: self.exciter_drive,
            spatial_width: self.spatial_width,
            spatial_depth: self.spatial_depth,
            spatial_crossfeed: self.spatial_crossfeed,
            spatial_mode: if self.spatial_mode_headphone {
                SpatialMode::HeadphonesBinaural
            } else {
                SpatialMode::LaptopSpeakers
            },
            earphone_type: EarphoneType::AirPodsAndTws,
            environment_mode: EnvironmentMode::CityTraffic,
            transient_attack: self.transient_attack,
            compressor_intensity: self.compressor_intensity,
            dynamic_loudness: self.dynamic_loudness,
        }
    }
}

pub fn get_default_presets() -> Vec<Preset> {
    vec![
        Preset {
            name: "Dolby Atmos Cinema 3D".to_string(),
            description: "Deep cinematic sub-bass, crystal clear dialogue presence, immersive 3D surround soundfield.".to_string(),
            eq_gains_10: [4.5, 3.8, 2.0, -0.5, 0.0, 1.5, 2.8, 3.5, 4.0, 4.5],
            master_gain_db: 1.0,
            ai_boost_enabled: true,
            ai_intensity: 0.9,
            bass_boost_intensity: 1.1,
            bass_speaker_protect: false,
            exciter_air_mix: 0.65,
            exciter_drive: 0.7,
            spatial_width: 1.55,
            spatial_depth: 0.55,
            spatial_crossfeed: 0.45,
            spatial_mode_headphone: true,
            transient_attack: 0.5,
            compressor_intensity: 0.75,
            dynamic_loudness: 0.6,
        },
        Preset {
            name: "Bang & Olufsen Signature".to_string(),
            description: "BeoPlay acoustic warmth, silky smooth crystal highs, spacious soundstage, and non-fatiguing rich bass.".to_string(),
            eq_gains_10: [3.5, 2.8, 1.2, 0.5, -0.8, 0.5, 1.8, 2.5, 4.5, 5.0],
            master_gain_db: 0.5,
            ai_boost_enabled: true,
            ai_intensity: 0.85,
            bass_boost_intensity: 0.85,
            bass_speaker_protect: false,
            exciter_air_mix: 0.75,
            exciter_drive: 0.55,
            spatial_width: 1.4,
            spatial_depth: 0.4,
            spatial_crossfeed: 0.5,
            spatial_mode_headphone: true,
            transient_attack: 0.35,
            compressor_intensity: 0.55,
            dynamic_loudness: 0.5,
        },
        Preset {
            name: "Apple Spatial Air & Punch".to_string(),
            description: "Modern punchy low-end, crisp vocal clarity, transparent spatial imaging, and pristine sparkle.".to_string(),
            eq_gains_10: [4.0, 3.2, 1.5, 0.0, -0.5, 1.2, 2.0, 3.0, 4.2, 4.8],
            master_gain_db: 0.0,
            ai_boost_enabled: true,
            ai_intensity: 0.8,
            bass_boost_intensity: 0.8,
            bass_speaker_protect: false,
            exciter_air_mix: 0.6,
            exciter_drive: 0.6,
            spatial_width: 1.35,
            spatial_depth: 0.3,
            spatial_crossfeed: 0.4,
            spatial_mode_headphone: true,
            transient_attack: 0.45,
            compressor_intensity: 0.65,
            dynamic_loudness: 0.45,
        },
        Preset {
            name: "Laptop Speaker Resonator Fix".to_string(),
            description: "Rescues tiny laptop speakers: demuds boxy chassis resonance, generates psychoacoustic sub-bass, and widens stereo.".to_string(),
            eq_gains_10: [-6.0, -2.0, 3.5, -4.5, -3.0, 2.0, 3.5, 4.5, 5.5, 6.0],
            master_gain_db: 2.0,
            ai_boost_enabled: true,
            ai_intensity: 1.0,
            bass_boost_intensity: 1.4,
            bass_speaker_protect: true, // protects small laptop speakers from blowing out
            exciter_air_mix: 0.85,
            exciter_drive: 0.8,
            spatial_width: 1.6,
            spatial_depth: 0.25,
            spatial_crossfeed: 0.0,
            spatial_mode_headphone: false, // Laptop acoustic lens mode
            transient_attack: 0.7,
            compressor_intensity: 0.85,
            dynamic_loudness: 0.8,
        },
        Preset {
            name: "DTS:X Spatial Gaming 3D".to_string(),
            description: "Pinpoint footstep audio, snappy gunshot transients, expansive 360 directional imaging, and explosive bass rumble.".to_string(),
            eq_gains_10: [3.0, 2.5, 1.0, -1.0, 0.5, 2.5, 4.0, 3.5, 4.0, 3.5],
            master_gain_db: 1.0,
            ai_boost_enabled: true,
            ai_intensity: 0.9,
            bass_boost_intensity: 0.9,
            bass_speaker_protect: false,
            exciter_air_mix: 0.7,
            exciter_drive: 0.65,
            spatial_width: 1.65,
            spatial_depth: 0.45,
            spatial_crossfeed: 0.35,
            spatial_mode_headphone: true,
            transient_attack: 0.85, // Super snappy
            compressor_intensity: 0.7,
            dynamic_loudness: 0.5,
        },
        Preset {
            name: "Audiophile Reference Headphones".to_string(),
            description: "Harman target reference curve, ultra-low distortion, natural Meier binaural crossfeed for zero listening fatigue.".to_string(),
            eq_gains_10: [2.5, 2.0, 0.5, -0.2, 0.0, 0.5, 1.2, 1.8, 2.2, 2.5],
            master_gain_db: 0.0,
            ai_boost_enabled: false,
            ai_intensity: 0.0,
            bass_boost_intensity: 0.2,
            bass_speaker_protect: false,
            exciter_air_mix: 0.2,
            exciter_drive: 0.2,
            spatial_width: 1.1,
            spatial_depth: 0.15,
            spatial_crossfeed: 0.6,
            spatial_mode_headphone: true,
            transient_attack: 0.1,
            compressor_intensity: 0.2,
            dynamic_loudness: 0.2,
        },
        Preset {
            name: "Vocal / Podcast / Dialogue Clarity AI".to_string(),
            description: "AI-enhanced speech intelligibility, eliminates vocal mud, enhances consonants, and suppresses room rumble.".to_string(),
            eq_gains_10: [-8.0, -4.0, -2.0, -1.5, 1.0, 3.5, 4.5, 3.0, 2.0, 1.0],
            master_gain_db: 1.5,
            ai_boost_enabled: true,
            ai_intensity: 1.0,
            bass_boost_intensity: 0.1,
            bass_speaker_protect: true,
            exciter_air_mix: 0.75,
            exciter_drive: 0.5,
            spatial_width: 1.0,
            spatial_depth: 0.1,
            spatial_crossfeed: 0.2,
            spatial_mode_headphone: true,
            transient_attack: 0.6,
            compressor_intensity: 0.8,
            dynamic_loudness: 0.3,
        },
        Preset {
            name: "Club / EDM / Hip-Hop Ultra Punch".to_string(),
            description: "Maximum sub-harmonic bass drive, chest-thumping transient kick snap, and club-shaking loudness contour.".to_string(),
            eq_gains_10: [6.5, 5.5, 3.0, -0.5, -1.0, 0.5, 2.0, 3.5, 4.5, 5.0],
            master_gain_db: 1.0,
            ai_boost_enabled: true,
            ai_intensity: 0.85,
            bass_boost_intensity: 1.5,
            bass_speaker_protect: false,
            exciter_air_mix: 0.6,
            exciter_drive: 0.7,
            spatial_width: 1.3,
            spatial_depth: 0.3,
            spatial_crossfeed: 0.3,
            spatial_mode_headphone: true,
            transient_attack: 0.8,
            compressor_intensity: 0.8,
            dynamic_loudness: 0.7,
        },
        Preset {
            name: "Acoustic / Classical Concert Hall".to_string(),
            description: "Spacious natural reverberant hall acoustic, wide dynamic range, organic string and woodwind shimmer.".to_string(),
            eq_gains_10: [1.5, 1.2, 0.8, 0.0, 0.2, 0.8, 1.5, 2.2, 3.5, 4.0],
            master_gain_db: 0.0,
            ai_boost_enabled: true,
            ai_intensity: 0.7,
            bass_boost_intensity: 0.4,
            bass_speaker_protect: false,
            exciter_air_mix: 0.55,
            exciter_drive: 0.35,
            spatial_width: 1.5,
            spatial_depth: 0.65,
            spatial_crossfeed: 0.45,
            spatial_mode_headphone: true,
            transient_attack: 0.2,
            compressor_intensity: 0.3,
            dynamic_loudness: 0.3,
        },
        Preset {
            name: "Flat Reference / Bypass".to_string(),
            description: "Clean uncolored passthrough for baseline reference and A/B comparison.".to_string(),
            eq_gains_10: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            master_gain_db: 0.0,
            ai_boost_enabled: false,
            ai_intensity: 0.0,
            bass_boost_intensity: 0.0,
            bass_speaker_protect: false,
            exciter_air_mix: 0.0,
            exciter_drive: 0.0,
            spatial_width: 1.0,
            spatial_depth: 0.0,
            spatial_crossfeed: 0.0,
            spatial_mode_headphone: true,
            transient_attack: 0.0,
            compressor_intensity: 0.0,
            dynamic_loudness: 0.0,
        },
    ]
}
